### ISSUE TITLE
Suggestion: --docdir option

### ISSUE THREAD

**Issue by mid-kid** [radare/acr#11]
Some distributions set their docdir to /usr/doc or something else. It'd be nice if acr supported that without having to write awkward sed lines to modify the Makefile.

**Comment by radare** [comment]
do you want a —docdir=DIR like its done for other flags too?

usually this is done with —datadir, but i understand that can be different..

**Comment by radare** [comment]
Fixed in 65586068d9a78d9edf16d5a7a22b1b1f0b733af9

**Comment by mid-kid** [comment]
Thanks!
